keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: demorealm
  resource: springboot-microservice
#  credentials:
#    secret: 9daa0e0c-6491-4d7d-801d-9cab084d1503
  principal-attribute: preferred_username
  ssl-required: external
  public-client: true
  use-resource-role-mappings: true
  bearer-only: true
  securityConstraints:
    - securityCollections:
        - name: course management
          patterns:
            - /customers
      authRoles: [user]
