keycloak:
  authServerUrl: http://localhost:8080/auth
  realm: university
  resource: course-management
  credentials:
    secret: feed05f8-c116-4744-b2ab-5baf601ce5e2
  principalAttribute: preferred_username
  sslRequired: external
  useResourceRoleMappings: true
  bearerOnly: true
  securityConstraints:
    - securityCollections:
        - name: course management
          patterns:
            - /courses/*
      authRoles: [teacher, ta, student, parent, coordinator]
    - securityCollections:
        - name: library resource
          patterns:
            - /library/*
      authRoles: [teacher, ta, student, parent, coordinator]
  policyEnforcerConfig:
    httpMethodAsScope: true
    paths:
      - path: /courses/{id}
        methods:
          - method: GET
            scopes: [view]
          - method: DELETE
            scopes: [delete]
      - path: /courses/{id}/coordinate
        methods:
          - method: GET
            scopes: [coordinate]
      - path: /library/{id}
        methods:
          - method: GET
            scopes: [view]
      - path: /greetings
        enforcementMode: DISABLED
